### ISSUE TITLE
Renommer l'onglet « Mon compte » en « Ma cagnotte »

### ISSUE THREAD

**Issue by JocelynDelalande** [Jojo144/compteur_du_gase#21]
« Compte » dans un contexte d'outil web c'est un peu confusant. À mon avis.

**Comment by JocelynDelalande** [comment]
Et puis c'est un mot sacrément moins drôle que Cagnotte.

**Comment by JocelynDelalande** [comment]
@Jojo144 Avis welcome :)

**Comment by Jojo144** [comment]
C'est formidable !
Je cherchais un synonyme depuis longtemps. "émolument" ça aurait pu être drôle mais c'est moins à propos.
Donc banco.

**Comment by JocelynDelalande** [comment]
OK, donc consensus pour renommer « le compteur du GASE » en « l'émolumenteur  du GASE » :clown_face:

**Comment by JocelynDelalande** [comment]
Je m'y colle
