### ISSUE TITLE
Pas sur que le script de restore  fonctionne

### ISSUE THREAD

**Issue by JocelynDelalande** [Jojo144/compteur_du_gase#32]
Scénario qui plante
https://paste.yunohost.org/raw/okevegepoj

- l'user lance une upgrade
- ynh fait un backup (qui semble marcher)
- ynh lance télécharge la nouvelle version et fait l'upgrade -> échec (pour une question d'accès à la base)
- ynh désinstalle l'app
- ynh tente de restaurer l'app (ça échoue)

Le problème le plus grave ici semble que la restauration ne fonctionne pas ça fait que si une upgrade échoue, ça désinstalle l'app et c'est tout.

Voici les lignes qui me semblent intéressantes par rapport à la restauration :

    2020-11-29 18:44:21,295: WARNING - 17929 /tmp/restoreSH86f6/restore: line 10: path: unbound variable

Très louche (je n'ai pas remplacé le domaine, ça écrit vraiment « compteur.domaine2.tld » :

    2020-11-29 18:44:21,296: DEBUG - 17929 + domain=compteur.domain2.tld

Dans la phase de backup, y'a ça qui ne sent pas bon aussi (mais ça n'a pas l'air de prêter à conséquence) :

    2020-11-29 18:42:58,867: WARNING - 614  /tmp/backup_NENfpE: line 3: _common.sh: No such file or directory

**Comment by Jojo144** [comment]
En règle général, faudrait vérifier les scripts backup/restore et faire changeurl

**Comment by JocelynDelalande** [comment]
Corrigé via #50
