### ISSUE TITLE
Bug dans le panier

### ISSUE THREAD

**Issue by Jojo144** [Jojo144/compteur_du_gase#63]
Sur la page d'achats :
- filtrer (genre "choc")
- remplir le champ de la nième ligne (genre du chocolat blanc) avec un nombre
- effacer le filtre (sans mettre dans le panier avant)

Bug : le nombre est toujours sur la nième ligne même si ce n'est plus du chocolat blanc.

Remarque : préexistait à #62

**Comment by JocelynDelalande** [comment]
Déjà corrigé par 46dbab4
