### ISSUE TITLE
YunoHost CI suggests some fixes

### ISSUE THREAD

**Issue by tituspijean** [Jojo144/compteur_du_gase#64]
Hello, and thank you for packaging this app and adding it to YunoHost's catalog!

We have an automated Continuous Integration system that runs tests on the apps, to make sure they are running alright in all possible configurations. This is the [report](https://ci-apps.yunohost.org/ci/job/5492) of the CI test.

You may find there some warning, errors, and suggestions to improve the app. ;)

(Edit: bon, je réalise que j'aurais pu écrire en français aussi... 😇 )

**Comment by alexAubin** [comment]
(Also imho it would really be better to keep the upstream source separated from the yunohost package itself ... currently, yunohost packages are really not designed to cohabit with raw sources ... though maybe oneday™)

**Comment by JocelynDelalande** [comment]
@alexAubin c'est pas très élégant effectivement, ça ne pose pas trop de soucis pratique pour l'instant à ma connaissance (si ça n'est le nom du repo), et ça réduit un peu le boulot de maintenance.

Vivement le dossier `.yunohost` par les laboratoires oneday™ alors :)

**Comment by JocelynDelalande** [comment]
Plus le bon endroit pour ça ➡ https://github.com/YunoHost-Apps/compteur_du_gase_ynh
