### ISSUE TITLE
le tableau ne classe pas les éléments par ordre de prix

### ISSUE THREAD

**Issue by Jojo144** [Jojo144/compteur_du_gase#71]
le tableau ne classe pas les éléments par ordre de prix croissant/décroissant, mais par ordre alphanumérique.
Exemple : quand on clique sur le titre d'une colonne "Prix", il affiche :
- 14.38 € / kg
- 2.02 € / kg
- 2.10 € / à l'unité
- etc.

**Comment by JocelynDelalande** [comment]
Et en plus l'ordre de tri est inversé :).
