### ISSUE TITLE
Creation de nouvelle catégorie

### ISSUE THREAD

**Issue by Abderazak-Amiar** [Jojo144/compteur_du_gase#72]
Ajouter une rubrique pour la création de nouvelle catégorie de produits

**Comment by JocelynDelalande** [comment]
@Abderazak-Amiar c'est déjà possible, il te suffit d'aller dans gestion/accès à l'interface d'administration puis « Catégories de produits ».

**Comment by JocelynDelalande** [comment]
N'hésite pas à ré-ouvrir le ticket si ça ne répond pas à ton besoin.

**Comment by JocelynDelalande** [comment]
@Abderazak-Amiar au fait, par curiosité, utilise-tu le compteur pour une asso qui n'est pas référencée dans le README ? Tu réponds si tu veux, pure curiosité :).
