### ISSUE TITLE
Appro : Afficher les produits masqués et permet l'update des prix.

### ISSUE THREAD

**Issue by JocelynDelalande** [Jojo144/compteur_du_gase#79]
ohé ohé

Le GASE à roulettes masque parfois les produits qui sont épuisés pour éviter de les choisir par accident en faisant ses courses. Par contre quand on ré-appro, c'est pénible car il n'apparaissent pas.

Donc proposition:

- sur la vue  d'appro : on met un bouton « Montrer les non visibles »… (Ou l'inverse d'ailleurs = montrer par défaut. À voir ce qui est le plus pertinent, mais c'est dur de présumer des pratiques des autres GASES),
- quand on approvisionne un produit non visible, on le rend visible automatiquement (on peut mettre un petit message pour expliciter ce fonctionnement)

**Comment by Jojo144** [comment]
Salut !
J'ai pris un peu le temps de réfléchir. À mon avis il faut mieux partir vers la première option car je pense qu'on ne peut jamais faire l'hypothèse que les stocks du logiciel reflète la réalité.
- Si il y a eu des erreur dans les appros / inventaires.
- Mais je crois qu'on peut même imaginer un GASE qui n'utilise pas du tout la fonction de suivi des stocks (j'ai l'exemple dans l'épicerie à côté de chez moi où, avec un autre logiciel, le stock de tous les produits est à une valeur négative arbitraire). D'ailleurs, dans l'idéal, il faudrait regarder si la vie de cet hypothétique GASE n'est pas trop pénible et même dans l'idéal idéal, faire une option pour masquer toutes les pages et éléments qui ne servent à rien.

Et d'ailleurs, tant qu'à bosser sur cette page, je trouverais ça trop bien de faire un champ "Modifier" à côté des petites infos sous chaque produit et notamment de pouvoir mettre à jour le stock en faisant un "inventaire monoproduit". Malheureusement je n'aurais pas le temps d'y bosser.

**Comment by JocelynDelalande** [comment]
> J'ai pris un peu le temps de réfléchir. À mon avis il faut mieux partir vers la première option car je pense qu'on ne peut jamais faire l'hypothèse que les stocks du logiciel reflète la réalité.

Je ne comprends pas trop ta remarque : rien dans mes propositions ne se base sur l'état du stock. Tu peux détailler car je crois qu'il y a quiproquo :).

**Comment by Jojo144** [comment]
Ah hou la la pardon ! J'ai réfléchi mais j'ai pas lu :-)

En effet on peut faire ce que tu proposes, ça parait cool. Je verrais bien un pop-up "Voulez-vous basculer bidule en visible ?" au moment où on approvisionne un non-visible.

Sinon j'imaginais que quand on clique sur "Montrer les non-visibles" un nouvelle colonne apparaît avec un bouton visible/non-visible pour chaque produit.

Ta proposition semble la meilleure je dirais. Sauf peut-être si on imagine un truc plus complet pour modifier les autres infos.

**Comment by JocelynDelalande** [comment]
Merci du retour :). Chantier en cours, mais pour l'instant ça ressemble à ça.

![image](https://user-images.githubusercontent.com/429633/233577302-5a7867b4-7573-4540-8315-67422d5a6cf5.png)


 Mais je vais peut-être bien reprendre ton idée d'une colone visible/invisible avec checkbox et qui pose la question « rendre visible ? »au moment où on appro un produit invisible.

Dans le top du top, il faudrait pouvoir éditer les autres infos du produit (dont référent) et ajouter des produits à la volée, mais c'est pas mal de taf donc non pour l'instant :-).
